### PR TITLE
Adds support for multiple interfaces

### PR DESCRIPTION
**Pull request by DerPeit**
This pull request adds the ability to monitor multiple lan interfaces and add dns entries accordingly. It adjusts the main script to accept an interface as a command line argument and adjusts upstream scripts (i.e. init script and ip6neigh binary) to launch multiple services, one per interface.

If you have some time to spend, feel free to review it. I did no extensive testing, though. I could have done better, but I cannot focus on this, currently. So if you're not willing to merge it, I am perfectly fine with it. Maybe it helps someone else as a head start on this topic.

### CODE REVIEW

**Comment by yfhyou** [comment]
@DerPeit Not sure if you are still around. This is from a long time ago!

I was trying to run this pull. I can't tell if its working because any `ip6neigh` command results in the following error: `/usr/bin/ip6neigh: line 131: HOSTS_FILE: is read only`. Or something similiar with a different line ##.

Also the log is really flooded with every combination of device / interface 'notices'. I have 4 interfaces and added the `option iface` to my static dhcp leases. So for every lease there are 3x lines of hosts being ignored on the other interaces.
```
user.notice ip6neigh: [br-lan.20] Host entry my-device will be ignored because it is connected to interface br-lan.10
user.notice ip6neigh: [br-lan.30] Host entry my-device will be ignored because it is connected to interface br-lan.10
user.notice ip6neigh: [br-lan.40] Host entry my-device will be ignored because it is connected to interface br-lan.10
```
not a huge deal, but it makes the log a bit difficult to follow if you have many static leases.

**Comment by cvmiller** [comment]
v1.7.3 includes the pull request changes (but not the version)

**Comment by yfhyou** [comment]
As far as I see multiple interfaces isn't enabled on the master branch... if I place multiple lines in my `/etc/config/ip6neigh` config like:
```
# LAN interface logical name. Default: 'lan'
         option lan_iface        'lan'
         option lan_iface        'guest'
```
only the last iface line is used. There is no documentation and the dhcp file does not read the `option iface` that was added in this PR.

**Comment by cvmiller** [comment]
You are correct, I saw the conflicts and thought that was the entire diff. 

Please resubmit your Pull Request with version 1.7.5 and I will merge the code.

**Comment by DerPeit** [comment]
Guys, I am still around. Thanks for asking. However, I am not sure when I have time to do this. When I have some time to spare I will have a look what changed from 1.7.3 to 1.7.5 and attempt to merge it.

**Comment by yfhyou** [comment]
I looked over it a bit and there are a couple conflicting changes with https://github.com/AndreBL/ip6neigh/pull/22 with the name of the lease file.

**Pull request closed without merging**
